name: fungid_flutter
description: The App for Fungid.app
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  google_fonts: ^2.1.0
  json_annotation: ^4.4.0
  path_provider: ^2.0.9
  image_picker: ^0.8.5
  fungid_api:
    path: packages/fungid_api
  openapi_generator_annotations: ^4.0.0
  uuid: 3.0.6
  image: 3.2.0
  shared_preferences: ^2.0.15
  carousel_slider: ^4.1.1
  geolocator: ^9.0.1
  geocoding: ^2.0.5
  google_maps_place_picker_mb: ^2.0.0-mb.22
  google_maps_flutter: ^2.2.0
  rxdart: ^0.27.5
  bloc: ^8.1.0
  dio: '>=4.0.1 <5.0.0'
  built_value: '>=8.1.0 <9.0.0'
  built_collection: '>=5.1.0 <6.0.0'
  flutter_pretty_dio_logger: '2.0.2'

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.3
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  mocktail: ^0.2.0
  openapi_generator: ^4.0.0
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/logo/icon.png'
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: 'assets/logo/icon.png'
    background_color: '#hexcode'
    theme_color: '#hexcode'
  windows:
    generate: true
    image_path: 'assets/logo/icon.png'
    icon_size: 48 # min:48, max:256, default: 48

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true
  assets:
    - assets/
