name: fungid_flutter
description: The App for Fungid.app
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  google_fonts: ^2.1.0
  equatable: ^2.0.3
  json_annotation: ^4.4.0
  path_provider: ^2.0.9
  camera: 0.10.0
  fungid_api:
    path: packages/fungid_api
  openapi_generator_annotations: ^4.0.0
  geolocator: ^9.0.1
  uuid: 3.0.6
  image: 3.2.0
  shared_preferences: ^2.0.15
  json_serializable: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.3
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  mocktail: ^0.2.0
  openapi_generator: ^4.0.0
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true
  assets:
    - assets/
